In [4]:
import numpy as np
np.random.random(4)*2 - 1

array([ 0.14723723,  0.50670628, -0.49605151,  0.40278656])

In [1]:
import gym
from sklearn.pipeline import FeatureUnion
from sklearn.preprocessing import StandardScaler
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDRegressor

In [2]:
env = gym.make('MountainCar-v0')

In [1]:
import torch

In [8]:
observation_examples = np.array([env.observation_space.sample() for x in range(2)])

scaler = StandardScaler()
scaler.fit(observation_examples)
n_components=4
# Used to converte a state to a featurizes represenation.
# We use RBF kernels with different variances to cover different parts of the space
featurizer = FeatureUnion([
        ("rbf1", RBFSampler(gamma=5.0, n_components=n_components)),
        ("rbf2", RBFSampler(gamma=2.0, n_components=n_components)),
        #("rbf3", RBFSampler(gamma=1.0, n_components=n_components)),
        #("rbf4", RBFSampler(gamma=0.5, n_components=n_components))
        ])
example_features = featurizer.fit_transform(scaler.transform(observation_examples))


In [9]:
observation_examples

array([[ 0.34818414,  0.03823591],
       [-0.49556834,  0.00253732]], dtype=float32)

In [10]:
example_features

array([[ 0.50676063,  0.51229592,  0.70672863, -0.67720721, -0.51713661,
         0.2040359 , -0.60760591, -0.43740927],
       [ 0.65788296, -0.58071268,  0.60652098,  0.48153577,  0.18307447,
        -0.30975474,  0.01084658,  0.56286128]])

In [11]:
example_features.shape[1]

8

In [12]:
np.random.randn(8) / np.sqrt(8)

array([-0.17976618, -0.08133366,  0.25599069,  0.71663188, -0.32836834,
       -0.31366198,  0.26765475, -0.1368554 ])

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])